### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by hamzahio** [BrianSipple/ember-stagger-swagger#4]
```
ember install ember-stagger-swagger
/Users/******/Desktop/*****/node_modules/ember-stagger-swagger/index.js:4
const path = require('path');
^^^^^
Use of const in strict mode.
/Users/******/Desktop/******/node_modules/ember-stagger-swagger/index.js:4
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Addon.lookup (/Users/******/Desktop/******/node_modules/ember-cli/lib/models/addon.js:879:19)
    at /Users/******/Desktop/******/node_modules/ember-cli/lib/models/addons-factory.js:47:36
    at visit (/Users/******/Desktop/******/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
```

there is problem when i want install ember-stagger-swagger with ember-cli v2.5.0

**Comment by BrianSipple** [comment]
What version of Node are you using? Using `const` should be supported in 4.x and higher.
